name: owmflutter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  validate: ^1.7.0
  built_collection: ^4.0.0
  shared_preferences: ^0.4.3
  built_value: ^6.1.4
  flutter_markdown: "^0.2.0"
  cupertino_icons: ^0.1.2
  http: ^0.11.3
  html: ^0.13.3+3
  dio: ^1.0.6
  path_provider: ^0.4.1
  html2md: ^0.2.1

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4


flutter:
  uses-material-design: true
  assets:
    - secrets.json