name: owmflutter
description: Unofficial wykop.pl client.

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.19.0
  pref_gen_annotations: ^0.0.1
  pref_gen_flutter: ^0.0.3
  validate: ^1.7.0
  built_collection: ^4.2.2
  shared_preferences: ^0.5.4+1
  built_value: ^6.7.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  image_picker: ^0.6.1+4
  flutter_advanced_networkimage: ^0.5.0
  video_player: ^0.10.2+1
  path_provider: ^1.3.0
  flutter_html: ^0.10.4
  flutter_inappbrowser: ^1.2.1
  redux_thunk: ^0.2.1
  timeago: ^2.0.17
  font_awesome_flutter: ^8.4.0
  transparent_image: ^1.0.0
  photo_view: ^0.4.2
  uuid: ^2.0.2
  share: ^0.6.2+1
  package_info: ^0.4.0+6
  bubble_tab_indicator: ^0.1.4
  color: ^2.1.1
  font_awesome: ^5.9.0
  provider: ^3.0.0
  intl: ^0.15.8
  flutter_material_color_picker: ^1.0.3
  esys_flutter_share: ^1.0.2
  mime: ^0.9.6+3
  image_downloader: ^0.19.0
  async: ^2.2.0
  background_fetch: ^0.3.2
  flutter_local_notifications: ^0.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  pref_gen: ^0.0.3
  build_runner: ^1.6.1
  built_value_generator: ^6.7.0

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#ff5f98f4"
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: OWMGlyphs
      fonts:
        - asset: assets/fonts/OWMGlyphs.ttf
  assets:
    - secrets.json
    - rogal.png
    - kosmo_bg.png
    - avatar.png
    - app_icon.png
    - no_picture.jpg
    - no_picture_night.jpg
