name: owmflutter
description: Unofficial wykop.pl client.

dependencies:
  flutter:
    sdk: flutter
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  validate: ^1.7.0
  built_collection: ^4.0.0
  shared_preferences: ^0.4.3
  built_value: ^6.1.4
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  html: ^0.13.3+3
  dio: ^1.0.6
  flutter_html_view: "^0.5.10"
  flutter_advanced_networkimage: ^0.3.9
  path_provider: ^0.4.1
  flutter_webview_plugin: ^0.2.1
  flutter_html: ^0.8.2
  flutter_inappbrowser: ^0.5.51
  redux_thunk: ^0.2.1
  timeago: ^2.0.9
  font_awesome_flutter: ^8.1.0
  cached_network_image: ^0.5.0
  transparent_image: ^0.1.0
  photo_view: ^0.0.10
  uuid: ^1.0.3
  share: ^0.5.3
  package_info: ^0.3.2
  flutter_custom_tabs: ^0.4.0
  bubble_tab_indicator: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  built_value_generator: ^6.1.4

flutter_icons:
  android: "launcher_icon" 
  adaptive_icon_background: "#ff5f98f4"
  ios: true
  image_path: "assets/rogal.png"

flutter:
  uses-material-design: true
  fonts:
    - family: OWMGlyphs
      fonts:
       - asset: fonts/OWMGlyphs.ttf
  assets:
    - secrets.json
    - rogal.png